In [1]:
import fastavro
from matplotlib.pyplot import table

a = 0

In [2]:
# !pip install pyarrow fastavro

Collecting pyarrow
  Downloading pyarrow-25.0.1-cp310-cp310-manylinux_2_28_x86_64.whl.metadata (3.0 kB)
Collecting fastavro
  Downloading fastavro-1.12.2-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (5.8 kB)
Downloading pyarrow-25.0.1-cp310-cp310-manylinux_2_28_x86_64.whl (50.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.1/50.1 MB 2.3 MB/s  0:00:21m0:00:0100:01
Downloading fastavro-1.12.2-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (3.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 2.3 MB/s  0:00:01 eta 0:00:01
Installing collected packages: pyarrow, fastavro
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [fastavro]1/2 [fastavro]
Successfully installed fastavro-1.12.2 pyarrow-25.0.1

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: pip install --upgrade pip

In [3]:
import pandas as pd

In [4]:
data = [
    {'student_id': 1, 'name': 'ashish', 'department': 'cse', 'marks': 72.25, 'ispassed': True},
    {'student_id': 2, 'name': 'rahul', 'department': 'ece', 'marks': 81.50, 'ispassed': True},
    {'student_id': 3, 'name': 'priya', 'department': 'it', 'marks': 68.75, 'ispassed': True},
    {'student_id': 4, 'name': 'rohit', 'department': 'me', 'marks': 42.00, 'ispassed': False},
    {'student_id': 5, 'name': 'neha', 'department': 'cse', 'marks': 91.25, 'ispassed': True},
    {'student_id': 6, 'name': 'aman', 'department': 'civil', 'marks': 55.50, 'ispassed': True},
    {'student_id': 7, 'name': 'simran', 'department': 'ece', 'marks': 37.25, 'ispassed': False},
    {'student_id': 8, 'name': 'karan', 'department': 'it', 'marks': 76.00, 'ispassed': True},
    {'student_id': 9, 'name': 'divya', 'department': 'cse', 'marks': 88.50, 'ispassed': True},
    {'student_id': 10, 'name': 'mohit', 'department': 'me', 'marks': 49.75, 'ispassed': False},
    {'student_id': 11, 'name': 'anjali', 'department': 'civil', 'marks': 63.25, 'ispassed': True},
    {'student_id': 12, 'name': 'vikas', 'department': 'cse', 'marks': 34.50, 'ispassed': False},
    {'student_id': 13, 'name': 'pooja', 'department': 'it', 'marks': 79.75, 'ispassed': True},
    {'student_id': 14, 'name': 'sahil', 'department': 'ece', 'marks': 67.00, 'ispassed': True},
    {'student_id': 15, 'name': 'komal', 'department': 'civil', 'marks': 52.25, 'ispassed': True},
    {'student_id': 16, 'name': 'arjun', 'department': 'me', 'marks': 29.50, 'ispassed': False},
    {'student_id': 17, 'name': 'ravi', 'department': 'cse', 'marks': 95.00, 'ispassed': True},
    {'student_id': 18, 'name': 'tanya', 'department': 'it', 'marks': 73.50, 'ispassed': True},
    {'student_id': 19, 'name': 'deepak', 'department': 'ece', 'marks': 44.25, 'ispassed': False},
    {'student_id': 20, 'name': 'shreya', 'department': 'cse', 'marks': 86.75, 'ispassed': True},
]

In [8]:
df = pd.DataFrame(data)
df.head(5)

   student_id    name department  marks  ispassed
0           1  ashish        cse  72.25      True
1           2   rahul        ece  81.50      True
2           3   priya         it  68.75      True
3           4   rohit         me  42.00     False
4           5    neha        cse  91.25      True

In [9]:
df.to_csv('sample.csv', index=False)

In [12]:
df.to_json('sample_data22.json', orient='records', indent=4)

In [16]:
# Avro
import fastavro

In [41]:
import  json

schema = {
    "type": "record",
    "name": "Student",
    "fields": [
        {"name": "student_id", "type": "int"},
        {"name": "name", "type": "string"},
        {"name": "department", "type": "string"},
        {"name": "marks", "type": "float"},
        {"name": "ispassed", "type": "boolean"},
    ]
}

In [42]:
parsed_schema = fastavro.parse_schema(schema)

with open('sample_data2.json') as f:
    records = json.load(f)

In [29]:
records

[{'student_id': 1,
  'name': 'ashish',
  'department': 'cse',
  'marks': 72.25,
  'ispassed': True},
 {'student_id': 2,
  'name': 'rahul',
  'department': 'ece',
  'marks': 81.5,
  'ispassed': True},
 {'student_id': 3,
  'name': 'priya',
  'department': 'it',
  'marks': 68.75,
  'ispassed': True},
 {'student_id': 4,
  'name': 'rohit',
  'department': 'me',
  'marks': 42.0,
  'ispassed': False},
 {'student_id': 5,
  'name': 'neha',
  'department': 'cse',
  'marks': 91.25,
  'ispassed': True},
 {'student_id': 6,
  'name': 'aman',
  'department': 'civil',
  'marks': 55.5,
  'ispassed': True},
 {'student_id': 7,
  'name': 'simran',
  'department': 'ece',
  'marks': 37.25,
  'ispassed': False},
 {'student_id': 8,
  'name': 'karan',
  'department': 'it',
  'marks': 76.0,
  'ispassed': True},
 {'student_id': 9,
  'name': 'divya',
  'department': 'cse',
  'marks': 88.5,
  'ispassed': True},
 {'student_id': 10,
  'name': 'mohit',
  'department': 'me',
  'marks': 49.75,
  'ispassed': False},
 {'student_id': 11,
  'name': 'anjali',
  'department': 'civil',
  'marks': 63.25,
  'ispassed': True},
 {'student_id': 12,
  'name': 'vikas',
  'department': 'cse',
  'marks': 34.5,
  'ispassed': False},
 {'student_id': 13,
  'name': 'pooja',
  'department': 'it',
  'marks': 79.75,
  'ispassed': True},
 {'student_id': 14,
  'name': 'sahil',
  'department': 'ece',
  'marks': 67.0,
  'ispassed': True},
 {'student_id': 15,
  'name': 'komal',
  'department': 'civil',
  'marks': 52.25,
  'ispassed': True},
 {'student_id': 16,
  'name': 'arjun',
  'department': 'me',
  'marks': 29.5,
  'ispassed': False},
 {'student_id': 17,
  'name': 'ravi',
  'department': 'cse',
  'marks': 95.0,
  'ispassed': True},
 {'student_id': 18,
  'name': 'tanya',
  'department': 'it',
  'marks': 73.5,
  'ispassed': True},
 {'student_id': 19,
  'name': 'deepak',
  'department': 'ece',
  'marks': 44.25,
  'ispassed': False},
 {'student_id': 20,
  'name': 'shreya',
  'department': 'cse',
  'marks': 86.75,
  'ispassed': True}]

In [43]:

with open('students.avro', 'wb') as f:
    fastavro.writer(f, parsed_schema, records)

In [51]:
import pyarrow as pq

In [49]:
with open('students.avro', 'rb') as f:
    records = list(fastavro.reader(f))

In [52]:
table = pq.Table.from_pylist(records)

In [54]:
table

pyarrow.Table
student_id: int64
name: string
department: string
marks: double
ispassed: bool
----
student_id: [[1,2,3,4,5,...,16,17,18,19,20]]
name: [["ashish","rahul","priya","rohit","neha",...,"arjun","ravi","tanya","deepak","shreya"]]
department: [["cse","ece","it","me","cse",...,"me","cse","it","ece","cse"]]
marks: [[72.25,81.5,68.75,42,91.25,...,29.5,95,73.5,44.25,86.75]]
ispassed: [[true,true,true,false,true,...,false,true,true,false,true]]

In [55]:
pq.parquet.write_table(table, 'example.parquet')

In [60]:
import pyarrow as pq
table2 = pq.parquet.read_table('example.parquet')
table2.to_pandas()

    student_id    name department  marks  ispassed
0            1  ashish        cse  72.25      True
1            2   rahul        ece  81.50      True
2            3   priya         it  68.75      True
3            4   rohit         me  42.00     False
4            5    neha        cse  91.25      True
5            6    aman      civil  55.50      True
6            7  simran        ece  37.25     False
7            8   karan         it  76.00      True
8            9   divya        cse  88.50      True
9           10   mohit         me  49.75     False
10          11  anjali      civil  63.25      True
11          12   vikas        cse  34.50     False
12          13   pooja         it  79.75      True
13          14   sahil        ece  67.00      True
14          15   komal      civil  52.25      True
15          16   arjun         me  29.50     False
16          17    ravi        cse  95.00      True
17          18   tanya         it  73.50      True
18          19  deepak        ece  44.25     False
19          20  shreya        cse  86.75      True

In [61]:
len(table2)

20